### PR TITLE
Add support for custom communities

### PR DESCRIPTION
**Pull request by ebarkie**
Per https://github.com/ebarkie/blackhole-threats/issues/6, this adds support for specifying a custom community for each feed.

This also deprecates the `gobgpd.conf` TOML config file and replaces it with a new YAML config that contains both the GoBGP config and the new feeds.

Flag based feeds remain the same and  use the "\<global-as\>:666" community.   To use custom communities the feed must be declared in the YAML configuration.  Both the config and flag feeds may be used simultaneously.
 
Example:
```yaml
gobgp:
  global:
    config:
      as: 64512
      routerid: "192.168.1.1"
  neighbors:
    - config:
        neighboraddress: "192.168.1.1"
        peeras: 64512

feeds:  
- url: "https://example.com/abusech-feed"  
  community: "64512:100"  
- url: "https://example.com/spamhaus-feed"  
  community: "64512:200"  
```

Note that the original proposal included a friendly `name` and while I think this is a good idea, it required more effort to implement while retaining compatibility with the flag so I left it out for now.

### CODE REVIEW

**Comment by ebarkie** [comment]
Still need to test this, but it seems to mostly work...

**Comment by soakes** [comment]
This is amazing! very nice!

As for the friendly name, its no worries, thats what comments are for :)

**Comment by soakes** [comment]
> Awesome! Please let me know if you're able to test it some time (whenever you get around to it - **no rush**). Barring any problems I think this is decent enough to merge as-is.
> 
> Merry Christmas!

Sure, would love to, give me a few hours, still in the middle of some Christmas stuff, will report back when I can.  Thanks again for your hard work.

**Comment by soakes** [comment]
@ebarkie so initial reports looks really good, I can connect with 32 bit ASN as well as 16 bit, however, I noticed when using 32 bit ASN and also using the same for the community, it will error and wont start.

This below was just a quick test, need to sort lists out, but done this as a quick test.  Of cause if you replaced the `4200421337:666` with say `64512:666` it will start fine.

I am just about to test 16 bit ASN and the communities to make sure they are actually doing what we expect, but I suspect they are.  Know more soon and will update post when I have more info.

```
gobgp:
  global:
    config:
      as: 4200421337
      routerid: "10.29.10.100"
  neighbors:
    - config:
        neighboraddress: "10.29.10.1"
        peeras: 4200421337

feeds:
  - url: https://sslbl.abuse.ch/blacklist/sslipblacklist.txt
    community: 4200421337:666
  - url: https://lists.blocklist.de/lists/all.txt
    community: 4200421337:667
```

The above will fail with the following error:
```
Dec 23 17:18:30 mgmt01 systemd[1]: Started blackhole-threats.service - Blackhole threats BGP daemon.
Dec 23 17:18:30 mgmt01 blackhole-threats[611]: time="2024-12-23T17:18:30Z" level=info msg="BGP threat blackhole route server (version befa20b)"
Dec 23 17:18:30 mgmt01 blackhole-threats[611]: time="2024-12-23T17:18:30Z" level=fatal msg="Unable to parse feed config" error="malformed community: upper strconv.ParseUint: parsing \"4200421337\": value out of range"
Dec 23 17:18:30 mgmt01 systemd[1]: blackhole-threats.service: Main process exited, code=exited, status=1/FAILURE
Dec 23 17:18:30 mgmt01 systemd[1]: blackhole-threats.service: Failed with result 'exit-code'.
Dec 23 17:18:30 mgmt01 systemd[1]: blackhole-threats.service: Scheduled restart job, restart counter is at 5.
Dec 23 17:18:30 mgmt01 systemd[1]: Stopped blackhole-threats.service - Blackhole threats BGP daemon.
Dec 23 17:18:30 mgmt01 systemd[1]: blackhole-threats.service: Start request repeated too quickly.
Dec 23 17:18:30 mgmt01 systemd[1]: blackhole-threats.service: Failed with result 'exit-code'.
Dec 23 17:18:30 mgmt01 systemd[1]: Failed to start blackhole-threats.service - Blackhole threats BGP daemon.
```

**Comment by ebarkie** [comment]
Cool, thanks for the quick and thorough testing.  Glad it's working with the 16-bit ASN's!

I'm definitely no expert here but my understanding is that "standard communities" are limited to a 32-bit unsigned consisting of a 16-bit AS and a 16-bit action, which is all that the GoBGP community attribute allows.

To support encoding a 32-bit ASN I think we would need to use "large communities" which are 96-bits consisting of a 32-bit source AS, 32-bit action, and 32-bit target AS.  Again, no expert but that's what I'm reading and seeing in the GoBGP interface... Does this sound right?

How important is this for your setup?  We could add it but it's a little more work so I'd probably look at doing it as a separate iteration at some point further in the future.

**Comment by soakes** [comment]
> Cool, thanks for the quick and thorough testing. Glad it's working with the 16-bit ASN's!
> 
> I'm definitely no expert here but my understanding is that "standard communities" are limited to a 32-bit unsigned consisting of a 16-bit AS and a 16-bit action, which is all that the GoBGP community attribute allows.
> 
> To support encoding a 32-bit ASN I think we would need to use "large communities" which are 96-bits consisting of a 32-bit source AS, 32-bit action, and 32-bit target AS. Again, no expert but that's what I'm reading and seeing in the GoBGP interface... Does this sound right?
> 
> How important is this for your setup? We could add it but it's a little more work so I'd probably look at doing it as a separate iteration at some point further in the future.

I must admit, I am no expert either :) but I am sure someone who uses this must be.

As for how important it is to me, minimal tbh, 16 bit ASN's are working perfectly and for all my hardware they are mostly Mikrotik's and/or bird2 instances and both are not limited to 32bit only, so I think we are good.  AFAIK its only very old hardware thats limited.

Lets run with this and later down the road if others really want 32bit support, we can add that.  However, I do think maybe that you should add a note in the documentation saying that only 16 bit ASN's are fully supported, that should stop any possible confusion with people. 

FYI, I was only testing possible scenarios that I could think of which others may use.

**Comment by ebarkie** [comment]
Sounds good!  I'll open up an additional issue to track this limitation, and good call on mentioning it in the docs.

I thoroughly enjoy projects like this precisely because of what we uncovered-- it's fun to have a reason to dig into and learn more about the protocol.

I really appreciate the idea and the testing, and am thrilled you're finding this useful.

**Comment by soakes** [comment]
> Sounds good! I'll open up an additional issue to track this limitation, and good call on mentioning it in the docs.
> 
> I thoroughly enjoy projects like this precisely because of what we uncovered-- it's fun to have a reason to dig into and learn more about the protocol.
> 
> I really appreciate the idea and the testing, and am thrilled you're finding this useful.

Totally agree!

And no worries about the testing, its the very least I can do and again thank you for doing this.

**Pull request merged**
